name: Main CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-style:
    uses: ./.github/workflows/duster-fix-blame.yml
    permissions:
      contents: write

  prettier:
    uses: ./.github/workflows/prettier.yml
    permissions:
      contents: write

  static-analysis:
    needs: [code-style, prettier]
    uses: ./.github/workflows/static-analysis.yml

  rector:
    needs: static-analysis
    uses: ./.github/workflows/run-rector.yml

  pest-tests:
    needs: rector
    uses: ./.github/workflows/pest-tests.yml

  dusk-tests:
    needs: rector
    uses: ./.github/workflows/dusk-tests.yml

  ci-passed:
    needs: [pest-tests, dusk-tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All CI checks passed!"
